backend:
  name: github
  repo: amir00900/perans
  branch: main
  base_url: https://perans-gold-auth.aseyeed1.workers.dev
  auth_endpoint: auth

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
